//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailCAD.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RailCAD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušeno.
        /// </summary>
        public static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procházet....
        /// </summary>
        public static string DialogImportPoints_Browse {
            get {
                return ResourceManager.GetString("DialogImportPoints_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor:.
        /// </summary>
        public static string DialogImportPoints_FileName {
            get {
                return ResourceManager.GetString("DialogImportPoints_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import bodů z textového souboru.
        /// </summary>
        public static string DialogImportPoints_PointsImportFromTextFile {
            get {
                return ResourceManager.GetString("DialogImportPoints_PointsImportFromTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měřítko X:.
        /// </summary>
        public static string DialogImportPoints_ScaleX {
            get {
                return ResourceManager.GetString("DialogImportPoints_ScaleX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měřítko Y:.
        /// </summary>
        public static string DialogImportPoints_ScaleY {
            get {
                return ResourceManager.GetString("DialogImportPoints_ScaleY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měřítko Z:.
        /// </summary>
        public static string DialogImportPoints_ScaleZ {
            get {
                return ResourceManager.GetString("DialogImportPoints_ScaleZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posun X:.
        /// </summary>
        public static string DialogImportPoints_ShiftX {
            get {
                return ResourceManager.GetString("DialogImportPoints_ShiftX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posun Y:.
        /// </summary>
        public static string DialogImportPoints_ShiftY {
            get {
                return ResourceManager.GetString("DialogImportPoints_ShiftY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posun Z:.
        /// </summary>
        public static string DialogImportPoints_ShiftZ {
            get {
                return ResourceManager.GetString("DialogImportPoints_ShiftZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čísla bodů nebo rozsah:.
        /// </summary>
        public static string DialogPointSelection_PointNumbersOrRange {
            get {
                return ResourceManager.GetString("DialogPointSelection_PointNumbersOrRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr pro poznámku:.
        /// </summary>
        public static string DialogPointSelection_TagFilter {
            get {
                return ResourceManager.GetString("DialogPointSelection_TagFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte hodnotu.
        /// </summary>
        public static string DialogPrompt_TitleEnterValue {
            get {
                return ResourceManager.GetString("DialogPrompt_TitleEnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kóta.
        /// </summary>
        public static string EntityType_Dimension {
            get {
                return ResourceManager.GetString("EntityType_Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úsečka.
        /// </summary>
        public static string EntityType_Line {
            get {
                return ResourceManager.GetString("EntityType_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stala se chyba..
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny soubory.
        /// </summary>
        public static string FileHandling_AllFiles {
            get {
                return ResourceManager.GetString("FileHandling_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při načítání souboru:.
        /// </summary>
        public static string FileHandling_ErrorWhileLoadingFile {
            get {
                return ResourceManager.GetString("FileHandling_ErrorWhileLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při čtení souboru:.
        /// </summary>
        public static string FileHandling_ErrorWhileReadingFile {
            get {
                return ResourceManager.GetString("FileHandling_ErrorWhileReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor neobsahuje žádná platná data..
        /// </summary>
        public static string FileHandling_FileContainsNoValidData {
            get {
                return ResourceManager.GetString("FileHandling_FileContainsNoValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím vyberte platný soubor..
        /// </summary>
        public static string FileHandling_PleaseSelectValidFile {
            get {
                return ResourceManager.GetString("FileHandling_PleaseSelectValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte soubor s body.
        /// </summary>
        public static string FileHandling_SelectFileWithPoints {
            get {
                return ResourceManager.GetString("FileHandling_SelectFileWithPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textové soubory.
        /// </summary>
        public static string FileHandling_TextFiles {
            get {
                return ResourceManager.GetString("FileHandling_TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nápověda.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importovat.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příkaz zrušen..
        /// </summary>
        public static string InfoCommandCancelled {
            get {
                return ResourceManager.GetString("InfoCommandCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informace.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadováno kladné celé číslo..
        /// </summary>
        public static string InputCheck_NumberMustBePositiveInteger {
            get {
                return ResourceManager.GetString("InputCheck_NumberMustBePositiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivace licence byla zrušena..
        /// </summary>
        public static string LicenceActivationAborted {
            get {
                return ResourceManager.GetString("LicenceActivationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivační kód vložte do formuláře na webu: licence.railcad.cz
        ///Nejedná se o licenční klíč..
        /// </summary>
        public static string LicenceActivationCodeInsertIntoFormOnWeb {
            get {
                return ResourceManager.GetString("LicenceActivationCodeInsertIntoFormOnWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivace licence.
        /// </summary>
        public static string LicenceActivationDialogName {
            get {
                return ResourceManager.GetString("LicenceActivationDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivace licence selhala.
        ///Licenci lze obnovit příkazem: RCLICENCE.
        /// </summary>
        public static string LicenceActivationFailed {
            get {
                return ResourceManager.GetString("LicenceActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutno aktivovat licenci. Zkopírujte následující kód do aktivačního webu: licence.railcad.cz.
        /// </summary>
        public static string LicenceActivationStart {
            get {
                return ResourceManager.GetString("LicenceActivationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivace licence proběhla úspěšně!.
        /// </summary>
        public static string LicenceActivationSuccess {
            get {
                return ResourceManager.GetString("LicenceActivationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze otevřít webovou stránku. Prosím otevřete manuálně: https://licence.railcad.cz/.
        /// </summary>
        public static string LicenceCannotOpenWebPleaseOpenManually {
            get {
                return ResourceManager.GetString("LicenceCannotOpenWebPleaseOpenManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kód byl zkopírován do schránky..
        /// </summary>
        public static string LicenceCodeCopied {
            get {
                return ResourceManager.GetString("LicenceCodeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 Zkopírovat kód.
        /// </summary>
        public static string LicenceCopyCode {
            get {
                return ResourceManager.GetString("LicenceCopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatná licence - licenci lze obnovit příkazem: RCLICENCE.
        /// </summary>
        public static string LicenceInvalidWarning {
            get {
                return ResourceManager.GetString("LicenceInvalidWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít aktivační web.
        /// </summary>
        public static string LicenceOpenWebsite {
            get {
                return ResourceManager.GetString("LicenceOpenWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vložte licenční klíč: .
        /// </summary>
        public static string LicencePasteKey {
            get {
                return ResourceManager.GetString("LicencePasteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím zadejte licenční klíč..
        /// </summary>
        public static string LicencePleaseEnterLicenceKey {
            get {
                return ResourceManager.GetString("LicencePleaseEnterLicenceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chybějící údaj.
        /// </summary>
        public static string MissingValue {
            get {
                return ResourceManager.GetString("MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při vytváření bodů: .
        /// </summary>
        public static string PointTools_ErrorWhileCreatingPoint {
            get {
                return ResourceManager.GetString("PointTools_ErrorWhileCreatingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při mazání bodu: .
        /// </summary>
        public static string PointTools_ErrorWhileDeletingPoint {
            get {
                return ResourceManager.GetString("PointTools_ErrorWhileDeletingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při importu bodů: .
        /// </summary>
        public static string PointTools_ErrorWhileImportingPoints {
            get {
                return ResourceManager.GetString("PointTools_ErrorWhileImportingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při zpracování bodů: {0}.
        /// </summary>
        public static string PointTools_ErrorWhileProcessingPoints {
            get {
                return ResourceManager.GetString("PointTools_ErrorWhileProcessingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při čtení bodu: .
        /// </summary>
        public static string PointTools_ErrorWhileReadingPoint {
            get {
                return ResourceManager.GetString("PointTools_ErrorWhileReadingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souřadnice X.
        /// </summary>
        public static string PointTools_ImportDialogCoordinateX {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogCoordinateX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souřadnice Y.
        /// </summary>
        public static string PointTools_ImportDialogCoordinateY {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogCoordinateY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souřadnice Z.
        /// </summary>
        public static string PointTools_ImportDialogCoordinateZ {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogCoordinateZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musíte určit sloupce pro souřadnice X a Y..
        /// </summary>
        public static string PointTools_ImportDialogDetermineColumnsForCoordinatesXY {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogDetermineColumnsForCoordinatesXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte výchozí poznámku pro body:.
        /// </summary>
        public static string PointTools_ImportDialogEnterDefaultPointTag {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogEnterDefaultPointTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte číslo prvního bodu:.
        /// </summary>
        public static string PointTools_ImportDialogEnterNumberOf1stPoint {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogEnterNumberOf1stPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detekováno záhlaví:.
        /// </summary>
        public static string PointTools_ImportDialogHeaderDetected {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogHeaderDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import bodů z textového souboru:
        ///1. Vyberte soubor s body pomocí tlačítka Procházet.
        ///2. V rozbalovacích menu určete typ dat v každém sloupci.
        ///3. Nastavte měřítko a posun souřadnic (pokud je potřeba).
        ///4. Klikněte na Importovat pro vytvoření bodů ve výkresu.
        ///
        ///Podporované formáty:
        ///- Hodnoty oddělené mezerami nebo tabulátory
        ///- Soubory mohou obsahovat záhlaví
        ///- Souřadnice mohou používat desetinnou tečku nebo čárku
        ///- Musí být určeny alespoň sloupce X a Y
        ///
        ///Pokud soubor neobsahuje čísla bodů nebo poznám [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PointTools_ImportDialogHelpText {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nápověda - Import bodů.
        /// </summary>
        public static string PointTools_ImportDialogHelpTitle {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorovat.
        /// </summary>
        public static string PointTools_ImportDialogIgnore {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezena společná předpona čísel bodů.
        /// </summary>
        public static string PointTools_ImportDialogInfoCommonPrefixFound {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogInfoCommonPrefixFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tato předpona bude odstraněna pro zachování kompatibility..
        /// </summary>
        public static string PointTools_ImportDialogInfoThisPrefixWillBeDeleted {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogInfoThisPrefixWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo bodu.
        /// </summary>
        public static string PointTools_ImportDialogPointNumber {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogPointNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import bodů byl zrušen..
        /// </summary>
        public static string PointTools_ImportDialogPointsImportWasCancelled {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogPointsImportWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čtení {0} bodů dokončeno..
        /// </summary>
        public static string PointTools_ImportDialogReadingOfPointsHasFinished {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogReadingOfPointsHasFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začínám importovat body..
        /// </summary>
        public static string PointTools_ImportDialogStartingPointsImport {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogStartingPointsImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string PointTools_ImportDialogTag {
            get {
                return ResourceManager.GetString("PointTools_ImportDialogTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úspěšně smazáno: {0} bodů.
        /// </summary>
        public static string PointTools_InfoDeletedPointsCount {
            get {
                return ResourceManager.GetString("PointTools_InfoDeletedPointsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import {0} bodů dokončen..
        /// </summary>
        public static string PointTools_InfoPointsImportHasBeenCompleted {
            get {
                return ResourceManager.GetString("PointTools_InfoPointsImportHasBeenCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezeno {0} bodů..
        /// </summary>
        public static string PointTools_InfoXPointsFound {
            get {
                return ResourceManager.GetString("PointTools_InfoXPointsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte kolik procent bodů chcete smazat: .
        /// </summary>
        public static string PointTools_PromptEnterWhatPercentageOfPointsYouWannaDelete {
            get {
                return ResourceManager.GetString("PointTools_PromptEnterWhatPercentageOfPointsYouWannaDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte body.
        /// </summary>
        public static string PointTools_PromptSelectPoints {
            get {
                return ResourceManager.GetString("PointTools_PromptSelectPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte čísla bodů přímo nebo použijte tlačítko Ukaž pro výběr bodů ve výkresu.
        ///Můžete zadat čísla bodů jako jednotlivá čísla (např. 1,3,5) nebo jako rozsahy (např. 1-5).
        ///Použijte pole filtr pro filtrování bodů podle jejich poznámky. Použijte * jako zástupný znak pro odpovídající libovolné znaky.
        ///Pro vyhledání bodů s prázdnou poznámkou jednoduše klikněte do pole filtru a nechte ho prázdné..
        /// </summary>
        public static string PointTools_SelectionDialogHelpText {
            get {
                return ResourceManager.GetString("PointTools_SelectionDialogHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nápověda - výběr bodů.
        /// </summary>
        public static string PointTools_SelectionDialogHelpTitle {
            get {
                return ResourceManager.GetString("PointTools_SelectionDialogHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukaž.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentská verze - není určena pro komerční účely.
        /// </summary>
        public static string StudentLicenceWarning {
            get {
                return ResourceManager.GetString("StudentLicenceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úspěch.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zohlednit plochu trojúhelníků pro výpočet normál?.
        /// </summary>
        public static string TerrainModel_PromptConsiderTriangleAreaForNormals {
            get {
                return ResourceManager.GetString("TerrainModel_PromptConsiderTriangleAreaForNormals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vykreslit trojúhelníky?.
        /// </summary>
        public static string TerrainModel_PromptDrawTriangles {
            get {
                return ResourceManager.GetString("TerrainModel_PromptDrawTriangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte entitu modelu terénu:.
        /// </summary>
        public static string TerrainModel_PromptSelectEntityOfTerrainModel {
            get {
                return ResourceManager.GetString("TerrainModel_PromptSelectEntityOfTerrainModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte body terénu.
        /// </summary>
        public static string TerrainModel_PromptSelectTerrainPoints {
            get {
                return ResourceManager.GetString("TerrainModel_PromptSelectTerrainPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte terénní linie / stisknutím ENTER pokračujte dále.
        /// </summary>
        public static string TerrainModel_PromptSelectTerrainSegments {
            get {
                return ResourceManager.GetString("TerrainModel_PromptSelectTerrainSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model terénu byl vytvořen..
        /// </summary>
        public static string TerrainModel_TerrainModelHasBeenCreated {
            get {
                return ResourceManager.GetString("TerrainModel_TerrainModelHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezen smazaný bod modelu terénu. Opravte model terénu!.
        /// </summary>
        public static string TerrainModel_WarningDeletedPointFoundFixTerrainModel {
            get {
                return ResourceManager.GetString("TerrainModel_WarningDeletedPointFoundFixTerrainModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraná entita patří více modelům terénu. Upřesněte model výběrem jiné entity!.
        /// </summary>
        public static string TerrainModel_WarningSelectedEntityBelongsToMoreModels {
            get {
                return ResourceManager.GetString("TerrainModel_WarningSelectedEntityBelongsToMoreModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraná entita není součástí žádného modelu terénu!.
        /// </summary>
        public static string TerrainModel_WarningSelectedEntityIsNotPartOfAnyModel {
            get {
                return ResourceManager.GetString("TerrainModel_WarningSelectedEntityIsNotPartOfAnyModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poloměr oblouku R={0}m je menší než minimální {1}m.
        /// </summary>
        public static string TramProfile_ErrorArcRadiusIsSmallerThanMin {
            get {
                return ResourceManager.GetString("TramProfile_ErrorArcRadiusIsSmallerThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} nebyl nalezen..
        /// </summary>
        public static string TramProfile_ErrorFileHasNotBeenFound {
            get {
                return ResourceManager.GetString("TramProfile_ErrorFileHasNotBeenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze vygenerovat obrys vozidla v obloucích!.
        /// </summary>
        public static string TramProfile_ErrorTramProfileCouldNotBeCreated {
            get {
                return ResourceManager.GetString("TramProfile_ErrorTramProfileCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při načítání souboru {0}: .
        /// </summary>
        public static string TramProfile_ErrorWhileLoadingFile {
            get {
                return ResourceManager.GetString("TramProfile_ErrorWhileLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořeny obrysy tramvajového vozidla pro oblouk R={0}m..
        /// </summary>
        public static string TramProfile_InfoTramProfilesWereCreatedForArc {
            get {
                return ResourceManager.GetString("TramProfile_InfoTramProfilesWereCreatedForArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořeny obrysy tramvajového vozidla pro složený oblouk..
        /// </summary>
        public static string TramProfile_InfoTramProfilesWereCreatedForCompoundArc {
            get {
                return ResourceManager.GetString("TramProfile_InfoTramProfilesWereCreatedForCompoundArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak chcete vzdálenost vyznačit?.
        /// </summary>
        public static string TramProfile_PromptHowToShowDistance {
            get {
                return ResourceManager.GetString("TramProfile_PromptHowToShowDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte oblouk: .
        /// </summary>
        public static string TramProfile_PromptSelectArc {
            get {
                return ResourceManager.GetString("TramProfile_PromptSelectArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte {0}. křivku: .
        /// </summary>
        public static string TramProfile_PromptSelectPolyline {
            get {
                return ResourceManager.GetString("TramProfile_PromptSelectPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraná entita není oblouk!.
        /// </summary>
        public static string TramProfile_WarningSelectedEntityIsNotArc {
            get {
                return ResourceManager.GetString("TramProfile_WarningSelectedEntityIsNotArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraná entita není křivka!.
        /// </summary>
        public static string TramProfile_WarningSelectedEntityIsNotPolyline {
            get {
                return ResourceManager.GetString("TramProfile_WarningSelectedEntityIsNotPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPOZORNĚNÍ: .
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
